@startuml Генерация_лабиринта
start

:Создать Maze с начальными стенами;
:Инициализировать стек и массив посещенных клеток;
:Поместить (0,0) в стек;
:Отметить (0,0) как посещенную;

while (Стек не пуст?) is (Да)
  :Текущая = вершина стека;
  :Найти непосещенных соседей;
  
  if (Есть непосещенные соседи?) then (Да)
    :Выбрать случайного соседа;
    :Удалить стену между текущей и соседом;
    :Поместить соседа в стек;
    :Отметить соседа как посещенную;
  else (Нет)
    :Удалить из стека;
  endif
endwhile (Нет)

:Добавить тупики для усложнения;
:Проверить связность лабиринта;

if (Лабиринт связный?) then (Да)
  :Вернуть Maze;
else (Нет)
  :Откатить изменения;
  :Вернуть Maze;
endif

stop
@enduml
